apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edge-frontend
  name: edge-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: edge-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: edge-frontend
    spec:
      containers:
      - image: quay.io/fzdarsky/edge-frontend:latest
        imagePullPolicy: Always
        name: edge-frontend
        ports:
        - containerPort: 1337
          name: web
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      dnsPolicy: ClusterFirst
