kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafka
  labels:
    env: env-demo
spec:
  entityOperator:
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
    topicOperator:
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 250Mi
    userOperator:
      resources:
        limits:
          cpu: 400m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 250Mi
  kafka:
    config:
      offsets.topic.replication.factor: 1
    jvmOptions: {}
    listeners:
    - name: tcp
      port: 9092
      tls: false
      type: internal
    # metricsConfig:
    #   type: jmxPrometheusExporter
    #   valueFrom:
    #     configMapKeyRef:
    #       key: metrics
    #       name: env-ephemeral-2vhslz-1ef1e48d-metrics
    #       optional: false
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 600Mi
    storage:
      type: ephemeral
    version: 3.4.0
  zookeeper:
    replicas: 1
    resources:
      limits:
        cpu: 350m
        memory: 800Mi
      requests:
        cpu: 200m
        memory: 400Mi
    storage:
      type: ephemeral
