apiVersion: v1
kind: Service
metadata:
  labels:
    app: host-inventory
    service: db
    sub: local_db
  name: host-inventory-db
spec:
  ports:
  - name: database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: host-inventory
    service: db
    sub: local_db
  type: ClusterIP
