apiVersion: v1
kind: Secret
metadata:
  name: keycloak
data:
  bopurl: {{ .Values.db.bopurl | b64enc }}
  defaultUsername: {{ .Values.db.defaultUsername | b64enc }}
  defaultPassword: {{ .Values.db.defaultPassword | b64enc }}
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  version: {{ .Values.db.version | b64enc }}
type: Opaque
