apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-import
  labels:
    app: sso
    env-app: keycloak-realm-import
data:
  redhat-external-realm.json: {{ include "redhat-external-realm.json" . | b64enc }}
type: Opaque
