apiVersion: v1
kind: Service
metadata:
  name: edge-api-db
  labels:
    app: edge-api
    service: db
    sub: local_db
spec:
  ports:
  - name: database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: edge-api
    service: db
    sub: local_db
  type: ClusterIP
