apiVersion: v1
kind: Service
metadata:
  labels:
    app: env-demo
    env-app: env-demo-featureflags
  name: env-demo-featureflags
spec:
  ports:
  - name: featureflags
    port: 4242
    protocol: TCP
    targetPort: 4242
  selector:
    app: env-demo
    env-app: env-demo-featureflags
  type: ClusterIP
