apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mbop
    env-app: env-demo-mbop
  name: mbop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mbop
      env-app: env-demo-mbop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbop
        env-app: env-demo-mbop
    spec:
      containers:
      - env:
        - name: KEYCLOAK_SERVER
          value: {{ .Values.keycloak.url }}
        - name: KEYCLOAK_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak
        - name: KEYCLOAK_VERSION
          valueFrom:
            secretKeyRef:
              key: version
              name: keycloak
        image: {{ .Values.images.mbop }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8090
          timeoutSeconds: 2
        name: mbop
        ports:
        - containerPort: 8090
          name: service
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8090
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
