kind: Secret
apiVersion: v1
metadata:
  name: featureflags-db
data:
  connectionURL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.db.username .Values.db.password .Values.db.hostname .Values.db.port .Values.db.name | b64enc }}
  hostname: {{ .Values.db.hostname | b64enc }}
  name: {{ .Values.db.name | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  pgPass: {{ .Values.db.adminPassword | b64enc }}
  port: {{ .Values.db.port | b64enc }}
  username: {{ .Values.db.username | b64enc }}
type: Opaque
