apiVersion: v1
kind: Service
metadata:
  labels:
    app: mocktitlements
    env-app: env-demo-mocktitlements
  name: mocktitlements
spec:
  ports:
  - name: mocktitlements
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: auth
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mocktitlements
    env-app: env-demo-mocktitlements
  sessionAffinity: None
  type: ClusterIP
