images:
  mocktitlements: quay.io/cloudservices/mocktitlements:e24820c
  caddyPlugin: quay.io/cloudservices/crc-caddy-plugin:1c4882e

ingress:
  hostname: entitlements.apps.management-hub.redhat-et.edge-lab.net

bopUrl: http://mbop.demo.svc:8090
ssoUrl: http://sso.demo.svc:8080