kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-frontend
  labels:
    frontend: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: inventory
  template:
    metadata:
      labels:
        frontend: inventory
    spec:
      volumes:
        - name: config
          configMap:
            name: env-demo
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: fe-image
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
            - name: metrics
              containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /opt/app-root/src/build/chrome
            - name: config
              mountPath: /opt/app-root/src/build/stable/operator-generated
            - name: config
              mountPath: /opt/app-root/src/build/preview/operator-generated
          terminationMessagePolicy: File
          image: {{ .Values.images.insightsFrontend }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
