kind: Service
apiVersion: v1
metadata:
  name: inventory
  labels:
    frontend: inventory
spec:
  ports:
    - name: public
      protocol: TCP
      appProtocol: http
      port: 8000
      targetPort: 8000
    - name: metrics
      protocol: TCP
      appProtocol: http
      port: 9000
      targetPort: 9000
  type: ClusterIP
  sessionAffinity: None
  selector:
    frontend: inventory
