kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: redhat-external
  namespace: demo
  labels:
    app: sso
spec:
  realm:
    id: redhat-external
    realm: redhat-external
    enabled: true
    displayName: Red Hat External
  instanceSelector:
    matchLabels:
      app: sso
