apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    env-app: env-demo-minio
  name: minio
spec:
  ports:
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    env-app: env-demo-minio
  sessionAffinity: None
  type: ClusterIP
