apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    env: env-demo
    strimzi.io/cluster: kafka
  name: platform.inventory.system-profile
spec:
  config: {}
  partitions: 1
  replicas: 1
