apiVersion: v1
kind: Secret
metadata:
  name: caddy-config-host-inventory-service
data:
  bopurl: {{ .Values.bopUrl | b64enc }}
  keycloakurl: {{ .Values.ssoUrl | b64enc }}
  whitelist: ""
type: Opaque
