apiVersion: v1
kind: Secret
metadata:
  name: featureflags
data:
  adminAccessToken: {{ .Values.unleash.adminAccessToken | b64enc }}
  clientAccessToken: {{ .Values.unleash.clientAccessToken | b64enc }}
type: Opaque
