apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso
  labels:
    app: sso
spec:
  ingressClassName: openshift-default
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: sso
            port:
              name: keycloak
        path: /
        pathType: Prefix
  tls:
  - {}
