apiVersion: v1
kind: Service
metadata:
  name: mbop
  labels:
    app: mbop
    env-app: env-demo-mbop
spec:
  ports:
  - name: mbop
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: mbop
    env-app: env-demo-mbop
  sessionAffinity: None
  type: ClusterIP
