apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chrome-service
    service: db
    sub: local_db
  name: chrome-service-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chrome-service
      service: db
      sub: local_db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chrome-service
        service: db
        sub: local_db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: {{ .Values.db.username }}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.db.password }}
        - name: PGPASSWORD
          value: {{ .Values.db.adminPassword }}
        - name: POSTGRESQL_MASTER_USER
          value: {{ .Values.db.adminUsername }}
        - name: POSTGRESQL_MASTER_PASSWORD
          value: {{ .Values.db.adminPassword }}
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.db.name }}
        image: {{ .Values.images.postgresql }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: chrome-service-db
        ports:
        - containerPort: 5432
          name: database
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 1200m
            memory: 1Gi
          requests:
            cpu: 600m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: chrome-service-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: chrome-service-app
      serviceAccountName: chrome-service-app
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: chrome-service-db
