apiVersion: v1
kind: Secret
metadata:
  name: chrome-service-db
data:
  db.host: {{ .Values.db.hostname | b64enc }}
  db.name: {{ .Values.db.name | b64enc }}
  db.password: {{ .Values.db.password | b64enc }}
  db.port: {{ .Values.db.port | b64enc }}
  db.user: {{ .Values.db.username | b64enc }}
  hostname: {{ .Values.db.hostname | b64enc }}
  name: {{ .Values.db.name | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  pgPass: {{ .Values.db.adminPassword | b64enc }}
  port: {{ .Values.db.port | b64enc }}
  username: {{ .Values.db.username | b64enc }}
type: Opaque
