apiVersion: v1
kind: Secret
metadata:
  name: caddy-config-chrome-service-api
data:
  bopurl: {{ .Values.bopUrl | b64enc }}
  keycloakurl: {{ .Values.ssoUrl | b64enc }}
  whitelist: L2FwaS9jaHJvbWUtc2VydmljZS92MS9zdGF0aWMvKg==
type: Opaque
