apiVersion: v1
kind: Service
metadata:
  labels:
    app: chrome-service
    pod: chrome-service-api
  name: chrome-service-api
spec:
  ports:
  - appProtocol: http
    name: public
    port: 8000
    protocol: TCP
    targetPort: 8000
  - appProtocol: http
    name: auth
    port: 8080
    protocol: TCP
    targetPort: 8080
  - appProtocol: http
    name: metrics
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    pod: chrome-service-api
  sessionAffinity: None
  type: ClusterIP
