apiVersion: v1
kind: Service
metadata:
  labels:
    app: chrome-service
    service: db
    sub: local_db
  name: chrome-service-db
spec:
  ports:
  - name: database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: chrome-service
    service: db
    sub: local_db
  sessionAffinity: None
  type: ClusterIP
