apiVersion: v1
kind: Secret
metadata:
  name: minio
data:
  hostname: {{ .Values.objectStore.hostname | b64enc }}
  port: {{ .Values.objectStore.port | b64enc }}
  accessKey: {{ .Values.objectStore.accessKey | b64enc }}
  secretKey: {{ .Values.objectStore.secretKey | b64enc }}
type: Opaque
