apiVersion: v1
kind: Service
metadata:
  labels:
    app: env-demo
    service: db
    sub: feature_flags
  name: featureflags-db
spec:
  ports:
  - name: database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: env-demo
    service: db
    sub: feature_flags
  type: ClusterIP
