apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    env: env-demo
    strimzi.io/cluster: kafka
  name: platform.playbook-dispatcher.runner-updates
spec:
  config: {}
  partitions: 16
  replicas: 1
