apiVersion: v1
kind: Secret
metadata:
  name: insights-rbac
data:
  client-id: {{ .Values.secrets.principalProxyClientId | b64enc }}
  token: {{ .Values.secrets.insightsRbacToken | b64enc}}
type: Opaque
