apiVersion: v1
kind: Service
metadata:
  labels:
    app: rbac
    env-app: rbac-redis
  name: rbac-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: rbac
    env-app: rbac-redis
  sessionAffinity: None
  type: ClusterIP
