images:
  rbac: quay.io/cloudservices/rbac:14470ec
  posgresql: quay.io/cloudservices/postgresql-rds:12-9ee2984
  redis: quay.io/cloudservices/redis-ephemeral:6
  caddyPlugin: quay.io/cloudservices/crc-caddy-plugin:1c4882e

db:
  hostname: rbac-db.demo.svc
  port: "5432"
  adminUsername: postgres
  adminPassword: FZ9H9VkGCWpPeqBr
  name: rbac
  username: YiO0w9paf5ZkEDk0
  password: H3bnpAsg7hnzlnOS

secrets:
  djangoSecretKey: "11111111111111111111111111111111111111111111111111"
  principalProxyApiToken: "2222222222222222222222222222222222222222222222222222222222222222"
  principalProxyClientId: insights-rbac
  principalProxyEnv: stage
  principalProxyHost: mbop
  principalProxyPort: "8090"
  principalProxyProtocol: http
  principalProxySourceCert: "False"
  principalProxySslVerify: "False"
  sentryDsn: ""
  insightsRbacToken: "2222222222222222222222222222222222222222222222222222222222222222"

ingress:
  hostname: edge-api.apps.management-hub.redhat-et.edge-lab.net

rbacService:
  hostname: rbac-service.demo.svc

redis:
  hostname: rbac-redis.demo.svc

kafka:
  hostname: kafka-kafka-bootstrap.demo.svc

featureFlags:
  hostname: featureflags.demo.svc
  clientAccessToken: default:development.224fde79cd528ca59cc190e0d2bb677d

bopUrl: http://mbop.demo.svc:8090
ssoUrl: http://env-ephemeral-encnmy-keycloak.ephemeral-encnmy.svc:8080